### ISSUE TITLE
Spoiler - Passphrase for Steghide

### ISSUE THREAD

**Issue by Dostonbek1** [techgaun/ctf-writeups#1]
Hi,

I am curious what you put for passphrase when running steghide command. I couldn't get it working? I look forward to your response.

Thank you!

**Comment by techgaun** [comment]
Hey @Dostonbek1 I can not remember any more because I did this couple of years back. However, I am pretty sure its something related with the information provided during the previous steps.

**Comment by BennetKrz** [comment]
For everybody looking for the passphrase, it is the hex, convertet to ASCII from the MD5 Hash. Its "divisionbell"...
